### ISSUE TITLE
[BUG] 百度翻译现在应该是没法正常工作了

### ISSUE THREAD

**Issue by gamesgao** [GameShare/Fanyi#1]
看起来百度在它的翻译请求中也加入了token和sign，这两个部分也需要加入到请求中。虽然具体怎么生成的还不是很清楚。。。

**Comment by Long-Dream** [comment]
目前应该也许修复了www

**Comment by gamesgao** [comment]
我昨天试了试google好像本来就是可以的

**Comment by gamesgao** [comment]
哦哦，你改了那接口，另外百度的那个token难道不会过期啥的么，我看百度API的说明是说这个sign是有的算法的但是token需要申请，虽然不知道网页的token是怎么来的。

**Comment by Long-Dream** [comment]
网页的token的获取方法可以见一并上传的分析文件
至于会不会过期...先看着吧, 如果不行的话就动态获取token

**Comment by gamesgao** [comment]
停一下，文档为啥是docx

**Comment by gamesgao** [comment]
www

**Comment by gamesgao** [comment]
动态获取token才是正确方式www

**Comment by Long-Dream** [comment]
docx感觉更方便啊www

**Comment by gamesgao** [comment]
没法在网页上直接看啊啊啊啊，是时候学习md了

**Comment by Long-Dream** [comment]
虽然会md, 但果然还是觉得用word更顺手点www
特别是有大量图片的时候www

**Comment by Long-Dream** [comment]
虽然会md, 但果然还是觉得用word更顺手点www
特别是有大量图片的时候www

**Comment by Long-Dream** [comment]
虽然会md, 但果然还是觉得用word更顺手点www
特别是有大量图片的时候www

**Comment by Long-Dream** [comment]
网络突然抽风www

**Comment by gamesgao** [comment]
另外可以看看[这个](http://api.fanyi.baidu.com/api/trans/product/apidoc)
虽然不知道这里面的sign的生成算法和网页上 的是否相同，但是我估计应该是相同的，其实关键还是那个token。
好吧虽然那个sign的算法没有token，但是我总感觉应该是一样的emmmm
好吧似乎不太一样

**Comment by gamesgao** [comment]
话说有道翻译和bing似乎也不能用欸

**Comment by gamesgao** [comment]
停一下，现在那个app.js中翻译的是哪里来的这么恐怖

**Comment by gamesgao** [comment]
还有那个superagent魔改是个什么鬼😂

**Comment by gamesgao** [comment]
另外我还发现+-3^+b+-f这个字符串在百度和google中都有出现，不知道是干啥的，神秘😱

**Comment by Long-Dream** [comment]
www
现在的可以先用着, 等不能用的时候在改www
有道和bing的那个...先放着吧www
来自于 chaos child 动画版中某一话的剧情简介www 士力架大爱
魔改那个....不用管就好www 历史遗留产物
那是宇宙之真理www
